spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
  server:
    ssl:
      enabled: true
      key-password: zaq1@WSX
      key-store-password: zaq1@WSX
      key-store: src/main/resources/keystore.jks
      key-store-type: pkcs12
