spring:
  profiles.active: ${KIPME_PROFILE:dev}
  data:
    redis:
      repositories:
        type: none
  datasource:
    url: ${DB_URL}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
    enabled: true
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
  port: 443

#jwt
app:
  jwtSecret: secretJWT
  jwtExpirationInMs: 3600000
  cache:
    available: true
    redis-url: ${REDIS_URL:redis://localhost:6379}
