spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  server:
    port: 443
    ssl:
      enabled: true
      key-password: zaq1@WSX
      key-store-password: zaq1@WSX
      key-store: src/main/resources/keystore.jks
      key-store-type: pkcs12
