spring:
  profiles.active: ${KIPME_PROFILE:dev}
  data:
    redis:
      repositories:
        type: none

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/kipme}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER:kipme}
    password: ${DB_PASSWORD:kipmesecret}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
    enabled: true
  flyway:
    enabled: true
    url: ${DB_URL:jdbc:mariadb://localhost:3306/kipme}
    user: ${DB_USER:kipme}
    password: ${DB_PASSWORD:kipmesecret}
    defaultSchema: kipme
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always

#jwt
app:
  jwtSecret: secretJWT
  jwtExpirationInMs: 3600000
  cache:
    available: true
    redis-url: ${REDIS_URL:redis://localhost:6379}
