version: "3.9"

services:
  db:
    image: mariadb:11.0.3
    container_name: kipme-db
    restart: always
    environment:
      MARIADB_ROOT_USER: ${DB_ROOT_USER}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - kipme-network

  redis:
    image: redis:7.2
    container_name: "kipme-redis"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - kipme-network

  kipme-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "kipme-backend"
    depends_on:
      - db
      - redis
    environment:
      KIPME_PROFILE: ${KIPME_PROFILE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:mariadb://kipme-db:${DB_PORT}/${DB_NAME}
      REDIS_URL: redis://kipme-redis:${REDIS_PORT}
    ports:
      - ${KIPME_PORT}:${KIPME_PORT}
    networks:
      - kipme-network

networks:
  kipme-network:
    driver: bridge